// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
/*const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  */
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
/*};

export default sidebars;
*/

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Fundamentos de JS',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-JSBasic',
        },
      ],
    },

    {
      type: 'category',
      label: 'Fundamentos de OO',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Tutorial-OOBasic',
        },
      ],
    },

    {
      type: 'category',
      label: 'JS Complementos',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-JSExtras',
        },
      ],
    },

    {
      type: 'category',
      label: 'Exercícios de Fixação',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-exercicios',
        },
      ],
    },

    {
      type: 'category',
      label: 'Exercícios Integradores',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-exercicio-integrador',
        },
      ],
    },
  ],
};

export default sidebars;